# Generated by Django 2.1.7 on 2019-11-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='creator',
            new_name='publisher',
        ),
    ]
