# Generated by Django 2.1.7 on 2019-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0002_auto_20191117_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(blank=True, max_length=50)),
                ('song_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='PlaylistSongs',
            new_name='AlbumSong',
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.FileField(blank=True, default='aa', upload_to='media/files/albumCovers/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.FileField(blank=True, default='aa', upload_to='media/files/albumCovers/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.FileField(blank=True, default='aa', upload_to='media/files/playlistCovers/'),
        ),
    ]
