# Generated by Django 2.1.7 on 2021-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0002_remove_creator_reveiwed_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='bl.Upload'),
        ),
    ]
