# Generated by Django 2.1.7 on 2019-11-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0004_auto_20191117_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=50)),
                ('album', models.CharField(blank=True, max_length=50)),
                ('albumartist', models.CharField(blank=True, max_length=50)),
                ('artist', models.CharField(blank=True, max_length=50)),
                ('audio_offset', models.CharField(blank=True, max_length=50)),
                ('bitrate', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('composer', models.CharField(blank=True, max_length=50)),
                ('disc', models.CharField(blank=True, max_length=50)),
                ('disc_total', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('filesize', models.CharField(blank=True, max_length=50)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('samplerate', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('track', models.CharField(blank=True, max_length=50)),
                ('track_total', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
