# Generated by Django 2.1.7 on 2019-11-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0006_auto_20191117_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
