# Generated by Django 2.1.7 on 2019-11-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0007_creator_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
