# Generated by Django 2.1.7 on 2019-11-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0008_auto_20191124_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
