# Generated by Django 2.1.7 on 2019-11-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0009_song_artist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_username',
        ),
    ]
