"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SITE_ID = 1

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n(_zb+=j2or8tjm16-@^-nmn1kyn3rl2fbglnw)c5w%5pl=hzh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['pod.pythonanywhere.com','localhost','*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
      'django.contrib.sites',
    'bl',
    'rest_framework',
    'rest_framework_docs',
     "social_django",
     'notify',
    #  'bootstrap_typeahead',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
       'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20, 
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'social_django.middleware.SocialAuthExceptionMiddleware',
  
]

AUTHENTICATION_BACKENDS = (
   
  'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
 'social_core.backends.google.GoogleOpenId',  # for Google authentication
 'social_core.backends.google.GoogleOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect', # <--
            ],
            'libraries':{
            'mytags': 'bl.mytags',
            }
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATA_UPLOAD_MAX_MEMORY_SIZE = 120000000


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static"),
# )



STATIC_ROOT = os.path.join(BASE_DIR, 'static')


LOGIN_REDIRECT_URL = 'bl:index'

LOGIN_URL = 'login'

LOGOUT_REDIRECT_URL = 'bl:index'
LOGOUT_URL = 'logout'



# LOGIN_REDIRECT_URL = 'dashboard'



# App Common Information
APP_EMAIL_FROM = 'omonaderrick25@gmail.com'
APP_URL_TOP_LOGO = BASE_DIR + 'static/assets/images/PinoyLearnPython-PLP.png'
APP_USER_AUTH_RE_ACCESS_LOGIN_PAGE = 'helloworld'

# Custom Password settings
MIN_PASS_LENGTH = 8
PASSWORD_RESET_TIMEOUT_DAYS = 1





# Google reCAPTCHA v3 api keys
GRECAP_SITE_KEY = '6LdHrN8UAAAAABi9eRSOwp5dCgh9WE8tWvUnFAUn'

# path_sk = BASE_DIR + '/static/bl/assets/GRECAP_SECRET_KEY.txt'
# read_sk = open(path_sk, "r")
# GRECAP_SECRET_KEY = read_sk.read()
# read_sk.close()


GRECAP_SECRET_KEY = '6LdHrN8UAAAAAPuS1gCwl2BLnQHSXwwg8bDhKZBg'


GRECAP_VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify'





MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# MEDIA_ROOT = 'media/'



SOCIAL_AUTH_URL_NAMESPACE = 'social'

# SOCIAL_AUTH_POSTGRES_JSONFIELD = True

SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = [                 
    ('name', 'name'),
    ('email', 'email'),
    ('picture', 'picture'),
    ('link', 'profile_url'),
] 

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "866068650147-eh40o0tk666cfujmiam7s8129cgjiivv.apps.googleusercontent.com" #Paste CLient Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "n_xcVC9wzWWf24fwriv0QghY" #Paste Secret Key


SOCIAL_AUTH_FACEBOOK_KEY = '1493502657467609'        # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'df8b20339c31ef06ee9c95497af5e510'  # App Secret


# SMTP Server Settings
# path_email = '/root/dev/config/email_pass.txt'
# # fem = open(path_email, "r")
# EMAIL_HOST_PASSWORD = fem.read()
# # fem.close()

# EMAIL_HOST = 'smtp.dreamhost.com'
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'your_email@domain.com'
# DEFAULT_FROM_EMAIL = 'support@pinoylearnpython.com'
# EMAIL_USE_SSL = True

# # SMTP for Production
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'omonaderrick25@gmail.com'
EMAIL_HOST_PASSWORD = 'gmail-password'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'